# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: f5eaf056f313269d5c8c9250e4b213bd7ea28958fec2edc7befc2fe74d66b8f1d2f336677b454df9faecaabcbded125efe11ab5776e85418dfae7d08b875f07d

test:
  domain_name: example.com 
  secret_key_base: 4761c52e21a33c35ff5ea7178047c81773ad5423f80480ad7bd9b72b3f2979f725cd199c284132af6effc5ec6655661df3943f1ec89f05c696706d40e01aabdd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
